language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t patrickdronk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true patrickdronk/docker-react npm run test

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: eu-central-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-719834252599"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY